---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5c799221ff164c0011c637a0/webhook/forestry'
sections:
  - type: document
    label: Global Site Config
    path: site-metadata.json
    templates:
      - config
  - type: document
    label: Home
    path: src/pages/index.md
    templates:
      - home
  - type: directory
    path: src/pages
    match: '**/*'
    exclude: '{posts/**,index.md}'
    label: Pages
    create: all
    templates:
      - page
  - type: directory
    path: src/pages/posts
    match: '**/*'
    label: Posts
    create: all
    templates:
      - post
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
